version: '2'
services:
  fs20toggler:
    image: arm32v7/node
    restart: always
    volumes:
      - ./:/src/
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    working_dir: /src
    command: node index.js 
